### ISSUE TITLE
beginner, use procedure on ubuntu 20.04 ..issues

### ISSUE THREAD

**Issue by fenix-soft** [seiferteric/remarkable_debfix#1]
hi, i manually downloaded the zip file from github from browser, then i tried to use your fix deb but using the command:

  dpkg-deb -Z xz -b old_deb remarkable_1.87_all.deb

gives me this error:

the control directory has wrong permissions: 700 (must be> = 0755 and <= 0775)

how do i fix? I'm on xubuntu 20.04
 
i know i could use the deb you created but i would like to try to figure out where i am going wrong trying to do it myself ...

thanks, if you want to help me ..

**Comment by seiferteric** [comment]
It looks like permissions were not preserved when unzipping the zip file. I did just try downloading the zip in Linux and didn't see this error, but it may depend on how or what you unzipped with. I would suggest using git clone instead.

**Comment by fenix-soft** [comment]
I solved it like this:
  ```
  cd remarkable_debfix/
  cd remarkable_debfix/ old_deb
```

at this point I changed the permissions on the DEBIAN folder (where there is the control file for the deb package, apparently it must have that kind of permission to be packaged by dpkg-deb) with:

    chmod -R 755 DEBIAN

then I managed to create the package. 

thanks for your interest and for creating this fix for remarkable
